### ISSUE TITLE
Some modifications required in the projects list in FAQ

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-welcome#101]
The [FAQ](https://welcome.realdevsquad.com/faq.html) page:
![image](https://user-images.githubusercontent.com/56217868/109956206-681f6e00-7d09-11eb-8f87-2559c7dc64e0.png)

Problems:
1. [Status](https://github.com/Real-Dev-Squad/website-status) site is missing which uses `Next.js, TypeScript`
2. `Members` site uses `Next.js`
3. `Main App` and `Events` are not currently being worked on, can be removed for now.
4. [My Site](https://github.com/Real-Dev-Squad/website-my) is missing which uses `Ember`
5. [Main Site](https://github.com/Real-Dev-Squad/website-www) is missing which uses `HTML, CSS, Javascript`

**Comment by ASHWINIAJIT** [comment]
Hello @swarajpure, I want to work on this issue.

Please assign it to me.

**Comment by Rucha1499** [comment]
Issue solved! Closing it,
