### ISSUE TITLE
Set up CI (Continuous Integration) using GitHub Actions

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-welcome#132]
We need to have CI using GitHub Actions which will run the `npm run check` script to check if the formatting of the code is correct or not.

Reference: https://docs.github.com/en/actions/guides/about-continuous-integration
Existing CI file from another project for reference: https://github.com/Real-Dev-Squad/website-backend/blob/develop/.github/workflows/test.yml

You'll have to setup CI in your fork of this repo first and then send a PR from there

**Comment by rahullli** [comment]
I would like to work on this issue .

**Comment by swarajpure** [comment]
Unassigning @rahullli as there were no updates from the user from 20 days after 4 reminders

**Comment by sebuelias** [comment]
I would like to try to take up this issue.
