### ISSUE TITLE
Adding `rel=noopener` / `rel=nonreferrar` to the external links in code.

### ISSUE THREAD

**Issue by Rucha1499** [Real-Dev-Squad/website-welcome#133]
We have the links to external sites in our application. For e.g : links to social media handles.

Adding `rel="noopener"` / `rel="nonreferrar"` to the external links in code will improve performance and prevent security vulnerabilities. Refer the image below. 👇 

![image](https://user-images.githubusercontent.com/66248039/111350471-28ad3600-86a8-11eb-90d0-34c004cf7864.png)

We can simply add - 
        `<a
            href="https://www.linkedin.com/company/real-dev-squad/"
            target="_blank" rel="noreferrer"
          >
            LinkedIn
          </a>`

**Comment by shetty-shithil** [comment]
This is a great method for preventing security vulnerabilities.
