### ISSUE TITLE
Bug in working of +/- icons on FAQ page.

### ISSUE THREAD

**Issue by Rucha1499** [Real-Dev-Squad/website-welcome#136]
![issue](https://user-images.githubusercontent.com/66248039/111578485-3e227d00-87da-11eb-984b-87271d328b3d.gif)

Refer the above video. The FAQ icons work as expected when clicked on that particular question. But if answer of one question is already open, and we click the other question, the previously opened answer minimizes but the corresponding `-` icon doesn't change back to `+`.  The expected working it the change in icons when answer is open/ closed.

Issue can be checked here : https://welcome.realdevsquad.com/faq.html

**Comment by iRahulP** [comment]
Hi @Rucha1499 , Can I start working on this issue?

**Comment by Rucha1499** [comment]
> Hi @Rucha1499 , Can I start working on this issue?

Sure!!

**Comment by iRahulP** [comment]
Hi @Rucha1499 ,
I have created a PR for this fix, but am not able to assign, and edit anything like adding reviewers.
https://github.com/Real-Dev-Squad/website-welcome/pull/145

Is there any access issue related to my profile as of which I am not able to edit it?

**Comment by Rucha1499** [comment]
Issue fixed via #145
