### ISSUE TITLE
Text of login btn position of navbar on small screen

### ISSUE THREAD

**Issue by Pavangbhat** [Real-Dev-Squad/website-welcome#137]
![image](https://user-images.githubusercontent.com/45538392/111588943-3b2f8880-87ea-11eb-940d-5edc5712dbc7.png)

### Text alignment of login button on small screen needs to be aligned according to burger menu

![image](https://user-images.githubusercontent.com/45538392/111588920-323eb700-87ea-11eb-8183-2e4e01b94b39.png)

pull request #138

**Comment by Rucha1499** [comment]
Fixed it!
