### ISSUE TITLE
Design Welcome site

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-welcome#139]
https://welcome.realdevsquad.com/

Currently our site lacks consistency in the elements and colors. We should make it awesome!

Mobile design also matters

**Comment by RezaHabibi1001** [comment]
Hi I will bring some changes in your project as soon as possible

**Comment by Hitendra10** [comment]
can i get assigned to this task?

**Comment by Rucha1499** [comment]
Issue fixed
