### ISSUE TITLE
Reduce font size for info note

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-welcome#141]
Reduce the font size for "info note" text to 20px

![image](https://user-images.githubusercontent.com/1935403/111662432-25f83100-87cd-11eb-8131-1e7272cce370.png)

**Comment by ptechofficial** [comment]
Can i work on this?

**Comment by ankushdharkar** [comment]
Yes @ptechofficial, thank you.
Assigning it to you.

**Comment by Rucha1499** [comment]
Issue solved in PR : #144
