### ISSUE TITLE
Removing the text with social media icons

### ISSUE THREAD

**Issue by ptechofficial** [Real-Dev-Squad/website-welcome#142]
I think having only social media icons is a more subtle approach rather than adding a text with them. 
![image](https://user-images.githubusercontent.com/64535754/111819732-b6865c80-8906-11eb-86af-5314929ce403.png)

**Comment by Rucha1499** [comment]
This page belongs to https://www.realdevsquad.com/. There is a separate repository for this project : https://github.com/Real-Dev-Squad/website-www. Can we have this issue over there?
