### ISSUE TITLE
Styling the links on the homepage

### ISSUE THREAD

**Issue by ptechofficial** [Real-Dev-Squad/website-welcome#143]
These links can be styled to suit the ambience of the home page
![image](https://user-images.githubusercontent.com/64535754/111820108-1bda4d80-8907-11eb-991e-3fbf097c6700.png)

**Comment by Rucha1499** [comment]
This page belongs to https://www.realdevsquad.com/. There is a separate repository for this project : https://github.com/Real-Dev-Squad/website-www. Can we have this issue over there?

**Comment by ptechofficial** [comment]
Yeah, sure!
