### ISSUE TITLE
Make the navbar logo smaller

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-welcome#158]
![image](https://user-images.githubusercontent.com/1935403/116597154-185cbd80-a8da-11eb-8f8a-a7ab8aec0146.png)

Please make it 50px X 50px

**Comment by imaxisXD** [comment]
I can take this task up

**Comment by swarajpure** [comment]
Unassigning imaxisXD for no further action

**Comment by ghosharnab969** [comment]
I am interested to take up the task
