### ISSUE TITLE
Make the navbar the same for all pages except external links

### ISSUE THREAD

**Issue by callapa1** [Real-Dev-Squad/website-welcome#160]
The navbar and its number of items change from page to page as it does its height. The logo doesn't show in all pages. There is different types of hover in different pages.

There should be only one navbar with one css that repeats in all pages.

**Comment by KhushalAbrol** [comment]
I can try, please assign me this issue.

**Comment by KhushalAbrol** [comment]
#163 please review

**Comment by Rucha1499** [comment]
Issue fixed in PR #201
