### ISSUE TITLE
Re-design of the welcome-site Navbar and Header

### ISSUE THREAD

**Issue by Rucha1499** [Real-Dev-Squad/website-welcome#169]
Welcome site is to be re-designed according to the design below. 👇 

Refer this figma link : https://www.figma.com/file/OBKehkbowYSTE7xAgsRx2m/Welcome-Page?node-id=0%3A1

The task is to design the `Navbar` and the `Header` below it.

Refer this image
![image](https://user-images.githubusercontent.com/66248039/127898224-07f81fe3-3df4-4a07-8c89-abc72d7bc6bf.png)

**Comment by ghosharnab969** [comment]
I would like to take up

**Comment by Utkarsh-droid** [comment]
I would  like to take up the issue

**Comment by Utkarsh-droid** [comment]
can you provide access to the image in header content

**Comment by swarajpure** [comment]
> I would like to take up the issue

The issue is already assigned to someone. Can you please look for an issue which is unassigned?
You can join our server to take up more of such tasks! Join us and upskill yourself 😄 
Join the discord server here: https://discord.gg/rWcb4bR4

**Comment by swarajpure** [comment]
@Utkarsh-droid

**Comment by yas-sisodia** [comment]
@Rucha1499 Please allow me to work on this project I can do this

**Comment by pranali-os** [comment]
hi, I wanted to make it mobile friendly. Assign me. :)

**Comment by Rucha1499** [comment]
Issue fixed
