### ISSUE TITLE
Re-design of welcome site - Part of site which contains links to docs and members page

### ISSUE THREAD

**Issue by Rucha1499** [Real-Dev-Squad/website-welcome#170]
We have a new design for https://welcome.realdevsquad.com/

Check it out here - https://www.figma.com/file/OBKehkbowYSTE7xAgsRx2m/Welcome-Page?node-id=0%3A1

Design the below mentioned part of welcome site referring to the above figma link.
![image](https://user-images.githubusercontent.com/66248039/127898924-4ee75a87-2467-48f5-8557-77dfbf1e3042.png)

**Comment by Ishikabaid** [comment]
I would like to take this up.
