### ISSUE TITLE
Re-design welcome site - Events, Introductory video section and footer.

### ISSUE THREAD

**Issue by Rucha1499** [Real-Dev-Squad/website-welcome#171]
We are having a new design for welcome site (https://welcome.realdevsquad.com/)

Check it out here - https://www.figma.com/file/OBKehkbowYSTE7xAgsRx2m/Welcome-Page?node-id=0%3A1

Referring to the above figma, design the below mentioned part of the page! 👇 
![image](https://user-images.githubusercontent.com/66248039/127899376-9705db5a-7f00-42c1-aa83-c3fb413d57f8.png)

**Comment by Pujarini** [comment]
Please assign this to my name

**Comment by Pujarini** [comment]
i would like to take this up

**Comment by yas-sisodia** [comment]
@Rucha1499 Please allow me to work on this Project I can do this

**Comment by NetanelK** [comment]
@Rucha1499 I can help
