### ISSUE TITLE
Remove capitalization of letters in each word in FAQ section.

### ISSUE THREAD

**Issue by Rucha1499** [Real-Dev-Squad/website-welcome#172]
![image](https://user-images.githubusercontent.com/66248039/128392702-1d8b5a22-d513-4a74-82c8-0cf8c1f77202.png)
In the above image you can see every first letter of word is Capital.

**Comment by Ardnetih10** [comment]
I would like to do this task.

**Comment by TheCoolGDev** [comment]
Can i do this task?

**Comment by Rucha1499** [comment]
Hey! @TheCoolGDev 
This issue was already assigned to @Hitendra10 and a PR is also raised for that. The issue will be closed now. 

You can find many such issues which are not assigned here - https://github.com/Real-Dev-Squad. Feel free join our discord server by using the following link - https://discord.gg/uuEEdf6s. Join us and upskill yourself! 🎉

**Comment by Rucha1499** [comment]
Fixed with #174
