### ISSUE TITLE
Add a line separator between question and answer for the last question in FAQ section

### ISSUE THREAD

**Issue by Rucha1499** [Real-Dev-Squad/website-welcome#173]
![image](https://user-images.githubusercontent.com/66248039/128395913-c6855da3-5f22-4e3a-8e0f-0c8cf67d39cb.png)

In the above image you can also see a blue line which acts as a separator between question and answer. It is missing in the last question. Please add it. Refer to the image below.

![image](https://user-images.githubusercontent.com/66248039/128393084-5ca5e732-b386-44f3-b740-529ffc6fc587.png)

**Comment by musabansari-1** [comment]
I would like to take up the task.

**Comment by arsheelsheikh** [comment]
I would like to do this task.

**Comment by yas-sisodia** [comment]
@Rucha1499  please allow me to work on this project I can do this
