### ISSUE TITLE
Make the FAQ page keyboard accessible

### ISSUE THREAD

**Issue by Rucha1499** [Real-Dev-Squad/website-welcome#176]
We have our FAQ page - https://welcome.realdevsquad.com/faq.html on welcome site. The question-answers on it are in the form of accordion. Currently, they can only be expanded/collapsed using mouse. We want to make them keyboard accessible.

This link can be used for reference - https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html

**Comment by ghosharnab969** [comment]
@Rucha1499 I would like to take up this task

**Comment by Ponmani-Geeky** [comment]
i would like to work on it ,please assign to me

**Comment by Ponmani-Geeky** [comment]
i can able to expand/collapse using keyboard space bar/Enter,so it's already working right?

**Comment by Chaitanya7666** [comment]
I wanted to contribute to the issue & when I checked [faq's page](https://welcome.realdevsquad.com/faq.html#How-do-I-join-the-squad), it seems to work pretty good. @Rucha1499, If there is anything else that I am missing out on, kindly guide me.

**Comment by DeRaowl** [comment]
@Rucha1499 can you assign this task to me
