### ISSUE TITLE
Add icon logo in the title bar. 

### ISSUE THREAD

**Issue by sheenachhabradev** [Real-Dev-Squad/website-welcome#18]
https://www.geeksforgeeks.org/how-to-add-icon-logo-in-title-bar-using-html/

**Comment by sheenachhabradev** [comment]
In photoshop we can create favicon
You can do this in illistratar or inkscape, wix, figma,invision
https://www.figma.com/ for design
https://www.wix.com/logo/maker

**Comment by ashishmangla0** [comment]
I am taking this can someone assing this to me?

**Comment by strider99** [comment]
Favicon added to the title.

![image](https://user-images.githubusercontent.com/7549876/89636623-8aaded80-d8c6-11ea-89b2-7847bbfbc509.png)
