### ISSUE TITLE
FAQs should be link-able

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-welcome#187]
On the FAQ page: https://welcome.realdevsquad.com/faq.html, if I wanted to give someone a link for a particular question, I can't do that. I have to give the link of whole page and then I have to mention which question to be looked after.

If you want to understand more on what I want to say, check the below links and observe the difference, they will take you different section on the same page:
- https://github.com/Real-Dev-Squad/website-welcome#want-to-contribute-or-learn-how-to
- https://github.com/Real-Dev-Squad/website-welcome#frequently-asked-questions

Figure out how this is being done and how can this be used in the FAQ page :)

**Comment by Manie-oss** [comment]
I will do it.
