### ISSUE TITLE
Fix FAQ page CSS in `develop` branch

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-welcome#190]
Currently we are redesigning the welcome site and the design is partially implemented. Whatever is implemented is merged in `develop` branch and is deployed to https://staging-welcome.realdevsquad.com, this code will eventually be merged to the `main` branch

Old, stable version of code is in `main` branch and is deployed to https://welcome.realdevsquad.com

Now if you see the FAQ page in both of the versions, something is broken. What is broken? That is up to you to find out and fix (pretty easy to identify if you compare both the versions side by side)

Links for you to compare:
https://staging-welcome.realdevsquad.com/faq.html
https://welcome.realdevsquad.com/faq.html

**Comment by ican8** [comment]
Can I work on this issue?
