### ISSUE TITLE
Add staging login link

### ISSUE THREAD

**Issue by akshay1502** [Real-Dev-Squad/website-welcome#192]
Change the production and staging login link according to environment.[here](https://github.com/Real-Dev-Squad/website-welcome/blob/259b3e223ab7955fa8bf0a97e8bde10809b91983/index.html#L84)
Link for production - https://github.com/login/oauth/authorize?client_id=23c78f66ab7964e5ef97
Link for staging - https://github.com/login/oauth/authorize?client_id=c4a84431feaf604e89d1

For reference https://github.com/Real-Dev-Squad/website-dashboard/pull/122#discussion_r775156545
https://github.com/Real-Dev-Squad/website-welcome/pull/198#issuecomment-991238725

**Comment by divyakelaskar** [comment]
Hey @akshay1502,
Can I work on this ?

**Comment by akshay1502** [comment]
> Hey @akshay1502, Can I work on this ?

Sure. I am assigning you this task. For any queries use `#welcome-site-vanilla` channel.

**Comment by divyakelaskar** [comment]
okay 👍

**Comment by akashbhadouria** [comment]
Hey @akshay1502 can you assign me this task?

**Comment by dhanush027** [comment]
Could you assign it to me

**Comment by NaincyKumariKnoldus** [comment]
Hey @akshay1502 Can I do this please?

**Comment by akshay1502** [comment]
> Hey @akshay1502 Can I do this please?

Really sorry, but this issue is assigned. You can look for other issues in the repo. Have you joined the discord server?

**Comment by NaincyKumariKnoldus** [comment]
No I haven't joined.

**Comment by akshay1502** [comment]
https://discord.gg/fvcKRpSG you can join the server using this link. @NaincyKumariKnoldus
