### ISSUE TITLE
Enhancement of the redesigned welcome site

### ISSUE THREAD

**Issue by Ishikabaid** [Real-Dev-Squad/website-welcome#194]
We are redesigning the welcome site and the basic design is implemented [here](https://staging-welcome.realdevsquad.com/) but there are a few things which we need to fix in order to implement the whole design successfully.

1. Right now there is a horizontal scroll on the site, we need to remove that.
2. We need to remove the underline on `check them out` text and align it with the adjacent arrow symbol, see the image below for the reference.
![Screenshot (378)](https://user-images.githubusercontent.com/59817624/142817386-4c68304f-e3b0-4758-a09b-afeff20ab020.png)

3. More space should be there between the image and the info paragraph, see the image below for reference.
![Screenshot (380)](https://user-images.githubusercontent.com/59817624/142817910-1717633b-7fbd-4ad3-904d-597ea7f7a7ed.png)

4. Right now the font here is not correct so need to change the font style. Also, the `pink` heading here should be bigger in size.
![Screenshot (381)](https://user-images.githubusercontent.com/59817624/142818139-c628d593-d068-40d0-a5e0-0451d4228999.png)

5. The RDS logo is not centered in the mobile view.
![Screenshot (382)](https://user-images.githubusercontent.com/59817624/142819429-43b1908d-9d9c-4cef-b5ae-9f388ec53fff.png)

Fix the above mentioned issues referring to this Figma design: https://www.figma.com/file/OBKehkbowYSTE7xAgsRx2m/Welcome-Page?node-id=0%3A1

**Comment by ambiexplores** [comment]
Hey! I can start working on the task

**Comment by ambiexplores** [comment]
@Ishikabaid ..PR created: https://github.com/Real-Dev-Squad/website-welcome/pull/195

**Comment by Rucha1499** [comment]
Fixed in PR - #201 #200
