### ISSUE TITLE
Fix alignment of social handle's logos

### ISSUE THREAD

**Issue by Rucha1499** [Real-Dev-Squad/website-welcome#197]
![image](https://user-images.githubusercontent.com/66248039/144858485-38a58e2e-d0ec-4d24-827d-5ac655fa6c74.png)

1) The logos of the social handles are not aligned properly with the text. It will look better if vertically centered.

refer : https://staging-welcome.realdevsquad.com/

**Comment by Rucha1499** [comment]
Issue solved in PR #195

**Comment by Youspeakcubic** [comment]
Hello, Could i work on this?

**Comment by Yogeshp0012** [comment]
Hey, Can I work on this?

**Comment by rohan09-raj** [comment]
@Youspeakcubic Assigning you the task.

**Comment by rohan09-raj** [comment]
> Hey, Can I work on this?

Sorry,  @Yogeshp0012, @Youspeakcubic  has asked first to work on this, so assigned to him/her. 
Would you both like to join our discord server, we are a community of developers where people learn and grow together. All levels are welcome.
Check out the website which is built by the developers of this community under the guidance of @ankushdharkar.
https://www.realdevsquad.com/
Discord:
https://discord.gg/wvqn96cw

**Comment by Yogeshp0012** [comment]
> > Hey, Can I work on this?
> 
> Sorry, @Yogeshp0012, @Youspeakcubic has asked first to work on this, so assigned to him/her. Would you both like to join our discord server, we are a community of developers where people learn and grow together. All levels are welcome. Check out the website which is built by the developers of this community under the guidance of @ankushdharkar. https://www.realdevsquad.com/ Discord: https://discord.gg/wvqn96cw

Its okay 🤗

**Comment by Youspeakcubic** [comment]
Hey @Yogeshp0012, Don't think ill be able to work on this for a while so you can work on it if you are still interested. Sorry for the delay, i will unassign myself.

**Comment by Rucha1499** [comment]
Fixed in PR #201
