### ISSUE TITLE
FAQs

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-welcome#2]
Let's start writing questions and their answers here.

**Comment by strider99** [comment]
Q - How do i contribute to RDS?

**Comment by strider99** [comment]
Q - I don't know GIT. Can  I still contribute ?

**Comment by ankushdharkar** [comment]
These two questions are enough to start. Let's add more questions after we have something on the page. Thanks guys!

**Comment by bharatgupta77** [comment]
okay !!!

**Comment by swarajpure** [comment]
Q. What is Real Dev Squad?

**Comment by swarajpure** [comment]
> 
> 
> Q. What is Real Dev Squad?

Real Dev Squad is a community of developers, where we come together to learn, use that in building projects, prepare for interviews, help each-other, put those projects online and try to help the set of new developers or freshers, helping them get better jobs and higher salaries with quality work. We come from all walks of lives and all kinds of background, with one thing in common: Wanting to work with others and improve ourselves.

**Comment by swarajpure** [comment]
> 
> 
> Q - How do i contribute to RDS?

As of now we're having 4 projects. Every project and the corresponding tech stack is mentioned below:

- [Welcome ](https://github.com/Real-Dev-Squad/website-welcome): HTML, CSS, Vanilla Javascript
- [Members ](https://github.com/Real-Dev-Squad/website-members): React
- [Events](https://github.com/Real-Dev-Squad/rds-events-website): React
- [Main ](https://github.com/Real-Dev-Squad/website-emberjs)App : Ember

Whatever project you wish to work on, hop on to the particular Discord channel and get started!

@ankushdharkar Can you please check if the links are correct?

**Comment by swarajpure** [comment]
Q. I get what is the squad about, but how do I join the squad?

**Comment by swarajpure** [comment]
> 
> 
> Q. I get what is the squad about, but how do I join the squad?

We communicate over a Discord channel. If you wish to join the Discord channel, please contact any of our members to get invitation link. 


---------------------------------------------------------------------------------------------------------
We can add the link to the members page, so that it'll be easier for the users to navigate.

**Comment by bharatgupta77** [comment]
@swarajpure i have using these question answer to see how everything looks .

**Comment by swarajpure** [comment]
Q. Where can I find the repository for Real Dev Squad?

**Comment by swarajpure** [comment]
> 
> 
> Q. Where can I find the repository for Real Dev Squad?

You can find all the projects under Real Dev Squad [here](https://github.com/Real-Dev-Squad).

**Comment by Rucha1499** [comment]
Questions for FAQ added. Closing this.
