### ISSUE TITLE
Centre Align Heading 

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-welcome#206]
In the desktop view of the `discord` page, the heading is not center-aligned. It needs to be center-aligned.
Check Image for reference
![image](https://user-images.githubusercontent.com/78433013/147872231-7bb7e473-3a7c-419d-a9d9-1cdd1aa669b6.png)

**Comment by priyanshk20** [comment]
I want to take up this task. Please assign
