### ISSUE TITLE
404 for Events site on Linked Pages

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-welcome#207]
When we go to any of the three pages `FAQ`, `Discord` and `Code of Conduct`,
![image](https://user-images.githubusercontent.com/78433013/147872313-d9a47bf5-cde8-43a3-8731-261697034bad.png)

then click on the `Events` tab in the navbar, we are getting a `404`.
![image](https://user-images.githubusercontent.com/78433013/147872331-19dce1f1-465f-4a9a-9b0d-0d239322d158.png)

URL for Events Page : `https://www.realdevsquad.com/events.html`

**Comment by shobit1337** [comment]
Hey @rohan09-raj, I would like to work on this one.
