### ISSUE TITLE
Fix the buttons for screen sizes from 426px - 670px and reduce the font size of heading

### ISSUE THREAD

**Issue by Rucha1499** [Real-Dev-Squad/website-welcome#212]
![image](https://user-images.githubusercontent.com/66248039/148574786-eaa2df0f-c894-4eeb-9d0c-662467ffed03.png)

- In the above image, we can that the buttons are not of same dimensions. The content in it won't allow 3 buttons in a row for smaller screen size (426px- 670px). Hence, we need to change the layout of buttons from row --> column. Please refer the below image for the same.

![image](https://user-images.githubusercontent.com/66248039/148575250-2cf01c05-884c-4f70-b0bf-14a0f380ef81.png)

- The font size of the text `Check Out Our Docs` looks a bit large. Please change it to `1.8rem` for screens between `426px - 670px`. Refer the below image.
![image](https://user-images.githubusercontent.com/66248039/148575842-2902d4db-4124-4dc2-863b-54276b7f818f.png)

**Comment by manavsiddharthgupta** [comment]
can you assign me.

**Comment by oneonone97** [comment]
Can you assign me the above task? Thank You!

**Comment by Sathasivamthirumoorthi** [comment]
I would like to work on this!
