### ISSUE TITLE
Make `Check them out` arrow clickable

### ISSUE THREAD

**Issue by Ishikabaid** [Real-Dev-Squad/website-welcome#224]
Ideally the arrow pointed out in the image should be clickable and should redirect us to https://www.realdevsquad.com/releases.
But it is not clickable at the moment, so we need to fix this.
![Screenshot (201)](https://user-images.githubusercontent.com/59817624/150679094-5888bd6a-1b20-4d6b-8dee-6ca2db4dbefe.png)

**Comment by anmoldewanrai** [comment]
I'd like to take this one.

**Comment by akash2819** [comment]
assign me

**Comment by anmoldewanrai** [comment]
Accidentally deleted the previous comment. Anyway, happy to contribute!

**Comment by Sathasivamthirumoorthi** [comment]
Since , I am new to open source , I would like to work on this.
