### ISSUE TITLE
Fix navbar display picture

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-welcome#229]
## Current Scenario
In the navbar of the welcome site, we are using the user image from [website-static](https://github.com/Real-Dev-Squad/website-static) 
![image](https://user-images.githubusercontent.com/78433013/172367770-d902b9ee-7576-4d1f-aab6-56e9ef182acf.png)

## Task
Instead of using an image of the user from website-static, we need to fetch it from the `/users/self` API and set the display picture from the response.

For Reference : Look into how other sites are doing it [website-www](https://github.com/Real-Dev-Squad/website-www/blob/develop/js/user.js)

Note : For accessing our APIs i.e. resolving CORS refer this [doc](https://github.com/Real-Dev-Squad/docs/tree/main/docs/dev/https-dev-url-cors)

**Comment by Mrityunjay1** [comment]
assign it to me will look into this
