### ISSUE TITLE
Links hover should be gradual

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-welcome#23]
Right now, the colors are quite flashy. We want to apply a transition to make them change in and out smoother for a better UX

![image](https://user-images.githubusercontent.com/1935403/113658777-86a0be00-9655-11eb-97a2-e8fe9084fad8.png)

**Comment by Devashish0210** [comment]
I'll help with this.

**Comment by Rucha1499** [comment]
Issue fixed!
