### ISSUE TITLE
Clicking on real dev squad logo should take the user to homepage

### ISSUE THREAD

**Issue by Maheima** [Real-Dev-Squad/website-welcome#239]
Currently, when you click on the logo, it doesn't do anything but it should be taking the user to homepage.

![image](https://user-images.githubusercontent.com/42349041/194092199-ad7b85a0-990d-4438-85ea-10ba4bc65ec5.png)

**Comment by kiran-thilak** [comment]
Hi, Can I work on this issue?

**Comment by Maheima** [comment]
Over to you. Please share the ETA

**Comment by kiran-thilak** [comment]
Will take 20 min to fix it and raise the PR.

**Comment by Maheima** [comment]
Awesome!
