### ISSUE TITLE
Update the FAQ page to match the branding

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-welcome#24]
Right now https://welcome.realdevsquad.com/faq looks out of place:

![image](https://user-images.githubusercontent.com/1935403/89216467-11717a80-d5e8-11ea-8371-f73f80fe30e7.png)

**Comment by karnsweta92** [comment]
I am picking this task.Kindly assign it.
CC: @ankushdharkar @sheenachhabradev

**Comment by Rucha1499** [comment]
FAQ page updated. Closing this issue!
