### ISSUE TITLE
[RFC] | Test Setup

### ISSUE THREAD

**Issue by vinit717** [Real-Dev-Squad/website-welcome#251]
##Issue
As there is no test setup in the welcome site for vanilla Js, we have to setup the test for it.

##Proposal
We can write tests with the help of Jest because of its simplicity.

**Comment by RitikJaiswal75** [comment]
Can we also have some other options?
Can we use jest and puppeteer together?
Jest can help us test the function and the puppeteer will give us an end-to-end view.

**Comment by vinit717** [comment]
> Can we also have some other options? Can we use jest and puppeteer together? Jest can help us test the function and the puppeteer will give us an end-to-end view.

Yes, we have other options vitest and mocha.
Yes, we can use jest and puppeteer together on the same project.
Yes It can but firstly we start with jest for a better coverage over all the tests
