### ISSUE TITLE
Fix typos on Code of Conduct page

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-welcome#38]
There are some typos on the CoC page: https://welcome.realdevsquad.com/code-of-conduct.html

This is a beginner-friendly issue.

Don't know how to proceed? This should help: https://github.com/Real-Dev-Squad/website-welcome/blob/main/CONTRIBUTING.md

Please comment down if you're going to work on this issue, so that it can be assigned to you.

**Comment by Rucha1499** [comment]
I can work on it. Can you please assign it to me?
