### ISSUE TITLE
Add margin to the h1 on the FAQ page

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-welcome#39]
There seems to be 0 margin between the navbar and h1 on the [FAQ](https://welcome.realdevsquad.com/faq.html) page:

![image](https://user-images.githubusercontent.com/56217868/89749301-bf978b80-dae4-11ea-9ce3-0f2d14de3c33.png)

This can be solved by adding `margin-top: 1em` to the h1 (make sure to give it an id and style that id, so in case we add one more h1 to the page, that wouldn't get affected)

![image](https://user-images.githubusercontent.com/56217868/89749393-2ddc4e00-dae5-11ea-90c2-1f8e98036988.png)

Read [this](https://github.com/Real-Dev-Squad/website-welcome/blob/main/CONTRIBUTING.md) if you're not comfortable with Git.

Please comment down if you're going to work on this issue, so that it can be assigned to you.

**Comment by Rucha1499** [comment]
I can work on it. Can you assign this to me?

**Comment by bharatgupta77** [comment]
Actually it has already been solved as there was styling given to h1 in main.css. No need.
