### ISSUE TITLE
Add transitition effects to FAQs expanding and collapsing

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-welcome#56]
On the [FAQ](https://welcome.realdevsquad.com/faq) page, the questions are expanding to show the answer, but it's not smooth, it's jerky.

![FAQs](https://i.imgur.com/hG8nPKa.gif)

It can fixed by adding some smooth transition (**hint**: transform property of CSS)

You can comment down if you want to take this up, so that it can be assigned to you.

**Comment by Biswa55** [comment]
Assigned to me,I will do it

**Comment by gauravchauhan2403** [comment]
@swarajpure  Is this issue still open. I would like to work on it.

**Comment by gauravchauhan2403** [comment]
is @biswajitripathy Still working on this.

**Comment by swarajpure** [comment]
There has been no reply from him since he has taken the issue. Transferring the issue to you now.

**Comment by gauravchauhan2403** [comment]
@swarajpure  Please Review it and suggest me changes if needed.

**Comment by gauravchauhan2403** [comment]
@swarajpure  @ankushdharkar  Another PR have Been made Please review it and merge.

**Comment by Rucha1499** [comment]
This issue is solved, Closing it.
