### ISSUE TITLE
Make questions on the FAQ page clickable

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-welcome#57]
As of now, only clicking on the + icon reveals the answer. If a user clicks on question, nothing happens.
It'd be better if the same behaviour is executed on clicking the question as well.

![FAQs-clicking](https://i.imgur.com/la1pcx2.gif)

Comment down here if you are going to work on this issue, so that it can be assigned to you.

**Comment by Biswa55** [comment]
I would like to work on this .. please assign me this

**Comment by gauravchauhan2403** [comment]
Please assign this to me. I would like to work on this

**Comment by gauravchauhan2403** [comment]
@swarajpure I have the Pull Request. Kindly review and merge it . Ask for any changes if required.

**Comment by gauravchauhan2403** [comment]
@swarajpure  I have opened the pull request. Kindly Review and Merge it. Ask for changes if required.

**Comment by swarajpure** [comment]
Issue solved. Closing issue.
