### ISSUE TITLE
Add new projects in FAQs

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-welcome#79]
Currently our FAQ section doesn't have `status` and `my` repos
Also, the main app should link to https://github.com/Real-Dev-Squad/website-www which is plain HTML, CSS
Status: https://github.com/Real-Dev-Squad/website-status : Which uses React, TypeScript
My: https://github.com/Real-Dev-Squad/website-my/ : Which uses Ember

**Comment by PremanandChowdhury** [comment]
Hey, I have made the changes and created a PR for the same do check and guide me for further changes if any.
Thank You.
Link: https://github.com/Real-Dev-Squad/website-welcome/pull/80
