### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by sheenachhabradev** [Real-Dev-Squad/website-welcome#8]
- We are dedicated to building a positive environment that inculcates open learning and high respect  for one another.

**Comment by strider99** [comment]
No trolling.
No spamming off topic stuff.
(In details)

**Comment by swarajpure** [comment]
If you've just joined the community, kindly introduce yourself in #newcomers channel.

Try to avoid DM'ing members for help. Use #support channel instead.

Try to avoid @everyone and @here unless something important/urgent/both.

**Comment by sheenachhabradev** [comment]
Google your queries. Before your seek help. 
When seeking help, Submit the code in an easy-to-evaluate fashion. Share a Codepen link instead of a Github link.
Overall challenge yourself. Take up tasks poractively and update your progress
It helps to have a picture on your discord & Github profiles.

**Comment by Rucha1499** [comment]
Done! Closing this issue.
