### ISSUE TITLE
Fix the FAQ page - Changing of +/- signs

### ISSUE THREAD

**Issue by Rucha1499** [Real-Dev-Squad/website-welcome#88]
- In the below image, the sign should be `-` when clicked on the question, according to desired behaviour.

![image](https://user-images.githubusercontent.com/66248039/109119509-cc22bf00-776a-11eb-8ce7-7e0b362f948e.png)

**Comment by ashwindevx** [comment]
I will fix the issue.✅ @Rucha1499

**Comment by TD-17** [comment]
Can I work on this issue ? @Rucha1499

**Comment by TD-17** [comment]
Have u assigned this issue to anyone ?  @Rucha1499

**Comment by Rucha1499** [comment]
@TD-17 I have assigned this issue to @ashwindevx as he commented on it first! Will get you new issue to solve.  Thank you. 😄 
.

**Comment by DaniManas** [comment]
I will work on this issue

**Comment by Rucha1499** [comment]
Assigned it to @DaniManas 👍

**Comment by DaniManas** [comment]
https://imgur.com/9pMxTsi
