### ISSUE TITLE
Change of Navigation bar for all the pages of welcome site.

### ISSUE THREAD

**Issue by Rucha1499** [Real-Dev-Squad/website-welcome#93]
We need to have a similar navbar for all the pages of the welcome site. Below mentioned is the desired design of navbar.

![image](https://user-images.githubusercontent.com/66248039/109320949-9a971a00-7876-11eb-91c0-5108cf60cd27.png)

We have this navbar on other projects in RDS and hence we should have similar one on welcome site.

![image](https://user-images.githubusercontent.com/66248039/109684289-232ef680-7ba6-11eb-9d86-2e525dc21dd4.png)

The above image shows the expected navbar. We want the same navbar with RDS logo instead of `Home` , and it should redirect user to https://www.realdevsquad.com/ when clicked. Also, we need the login button on the right end of navbar. The logic for login button is already written. Just integrate it with new navbar.

**Comment by swarajpure** [comment]
We need to have a discussion on this issue. Once that is done, this issue will be available to be picked up

**Comment by Rucha1499** [comment]
Issue solved in PR #102
