### ISSUE TITLE
Change in design of the home page of welcome site.

### ISSUE THREAD

**Issue by Rucha1499** [Real-Dev-Squad/website-welcome#99]
Below attached is the existing design of welcome site.
![image](https://user-images.githubusercontent.com/66248039/109694394-c422af00-7bb0-11eb-9499-d64bd35253e2.png)
 
We need to change it a bit.
- Move the text highlighted in blue colour below social media handles i.e  above the footer
- Remove the RDS logo
- Replace the logo with 3 cards/ boxes containing links to `FAQ`, `Discord` and `Code of Conduct` pages. Add the title as `Check out our Docs` for the cards.  We need to mention them there because they will be removed from navbar. Refer : #93 
- Below attached is the rough draft of new design.

![image](https://user-images.githubusercontent.com/66248039/109695217-a6097e80-7bb1-11eb-9ffe-fdae405f1998.png)

Thank you!

**Comment by TD-17** [comment]
Hey can I take this issue? @Rucha1499

**Comment by Rucha1499** [comment]
Sure @TD-17 🎉
